alias cls=clear
alias code='code-insiders'
alias cronlog='sudo cat /var/log/cron.log'
alias server='ssh steve@server'
alias ls='exa'
alias cat='bat'
alias df="df -x squashfs -x tmpfs -H"
alias copy='xclip -selection clipboard'
alias paste='xclip -selection clipboard -o'
alias vim='nvim'
